0,SyntaxError,"invalid syntax (844498984.py, line 1)",0,,2024-09-22 10:16:55.848991,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_6816/844498984.py"", line 1', '    characters_q1 = ', '                    ^', 'SyntaxError: invalid syntax']"
1,NameError,name 'plots' is not defined,0,,2024-09-22 11:03:24.842421,"[('plots.show()', 19)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_7373/884739542.py"", line 19, in <module>', '    plots.show()', ""NameError: name 'plots' is not defined""]"
2,AttributeError,'NoneType' object has no attribute 'show',0,,2024-09-22 11:35:47.239435,"[(').scatter(0).show()', 7)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_9659/3053717060.py"", line 7, in <module>', '    ).scatter(0).show()', ""AttributeError: 'NoneType' object has no attribute 'show'""]"
3,AttributeError,'NoneType' object has no attribute 'show',0,,2024-09-22 11:41:35.525006,"[('a.show()', 8)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_9659/3423128254.py"", line 8, in <module>', '    a.show()', ""AttributeError: 'NoneType' object has no attribute 'show'""]"
4,SyntaxError,"cannot assign to literal here. Maybe you meant '==' instead of '='? (2912417615.py, line 1)",0,,2024-09-22 15:29:25.202630,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_166/2912417615.py"", line 1', '    4 = 2 + 2', '    ^', ""SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='?""]"
5,SyntaxError,"invalid syntax (3853341378.py, line 2)",0,,2024-09-22 15:29:51.516638,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_166/3853341378.py"", line 2', '    six = two plus two', '              ^^^^', 'SyntaxError: invalid syntax']"
6,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2024-09-22 15:39:54.955778,"[('grader.check(""q4_2"")', 1), ('raise e', 217)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_166/894560666.py"", line 1, in <module>', '    grader.check(""q4_2"")', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/otter/check/utils.py"", line 217, in event_logger', '    raise e', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/otter/check/utils.py"", line 213, in event_logger', '    ret: Optional[LoggedEventReturnValue[T]] = wrapped(*args, **kwargs)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/otter/check/notebook.py"", line 280, in check', '    result = Checker.check(test_path, self._nbmeta_config, test_name, global_env)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/otter/execute/checker.py"", line 77, in check', '    test = create_test_file(nb_or_test_path, nbmeta_config, test_name=test_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/otter/test_files/__init__.py"", line 69, in create_test_file', '    raise RuntimeError(', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
7,SyntaxError,"invalid syntax (3853341378.py, line 2)",0,,2024-09-22 15:58:29.663366,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_463/3853341378.py"", line 2', '    six = two plus two', '              ^^^^', 'SyntaxError: invalid syntax']"
