0,NameError,name 'tbl' is not defined,0,,2024-10-08 14:35:55.781379,"[('tbl.show(3)', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/3040551073.py"", line 1, in <module>', '    tbl.show(3)', ""NameError: name 'tbl' is not defined""]"
1,ValueError,"The column ""Name"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time",0,,2024-10-08 14:42:44.880134,"[('farmers_markets_locations = farmers_markets.select(""Name"",""City"",""State"",""Latitude"",""Longitude"")', 1), ('self._add_column_and_format(table, label, np.copy(self[label]))', 1272)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/3760553083.py"", line 1, in <module>', '    farmers_markets_locations = farmers_markets.select(""Name"",""City"",""State"",""Latitude"",""Longitude"")', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 1272, in select', '    self._add_column_and_format(table, label, np.copy(self[label]))', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 281, in __getitem__', '    return self.column(index_or_label)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 448, in column', '    raise ValueError(', 'ValueError: The column ""Name"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time']"
2,ValueError,"The column ""City"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time",0,,2024-10-08 14:43:13.725236,"[('farmers_markets_locations = farmers_markets.select(""MarketName"",""City"",""State"",""Latitude"",""Longitude"")', 1), ('self._add_column_and_format(table, label, np.copy(self[label]))', 1272)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/3871334165.py"", line 1, in <module>', '    farmers_markets_locations = farmers_markets.select(""MarketName"",""City"",""State"",""Latitude"",""Longitude"")', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 1272, in select', '    self._add_column_and_format(table, label, np.copy(self[label]))', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 281, in __getitem__', '    return self.column(index_or_label)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 448, in column', '    raise ValueError(', 'ValueError: The column ""City"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time']"
3,ValueError,"The column ""Latitude"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time",0,,2024-10-08 14:43:27.019404,"[('farmers_markets_locations = farmers_markets.select(""MarketName"",""city"",""State"",""Latitude"",""Longitude"")', 1), ('self._add_column_and_format(table, label, np.copy(self[label]))', 1272)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/1379990195.py"", line 1, in <module>', '    farmers_markets_locations = farmers_markets.select(""MarketName"",""city"",""State"",""Latitude"",""Longitude"")', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 1272, in select', '    self._add_column_and_format(table, label, np.copy(self[label]))', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 281, in __getitem__', '    return self.column(index_or_label)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 448, in column', '    raise ValueError(', 'ValueError: The column ""Latitude"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time']"
4,NameError,name 'Rating' is not defined,0,,2024-10-08 15:12:12.291392,"[('above_eight = imdb.where(""Year"",are.between_or_equal_to(2010,2015)).where(""Rating"",are.above(8)).select(""Title"",Rating).sort(""Rating"",descending=True)', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/4169060205.py"", line 1, in <module>', '    above_eight = imdb.where(""Year"",are.between_or_equal_to(2010,2015)).where(""Rating"",are.above(8)).select(""Title"",Rating).sort(""Rating"",descending=True)', ""NameError: name 'Rating' is not defined""]"
5,NameError,name 'num_in_21th_century' is not defined,0,,2024-10-08 15:16:12.454950,"[('proportion_in_21st_century = num_in_21th_century/num_movies_in_dataset', 5)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/4164532500.py"", line 5, in <module>', '    proportion_in_21st_century = num_in_21th_century/num_movies_in_dataset', ""NameError: name 'num_in_21th_century' is not defined. Did you mean: 'num_in_20th_century'?""]"
6,AttributeError,'Table' object has no attribute 'num_row',0,,2024-10-08 15:18:05.329540,"[('num_movies_in_dataset = imdb.num_row', 1), ('raise AttributeError(msg)', 318)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_267/3897527321.py"", line 1, in <module>', '    num_movies_in_dataset = imdb.num_row', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 318, in __getattr__', '    raise AttributeError(msg)', ""AttributeError: 'Table' object has no attribute 'num_row'. Did you mean: 'num_rows'?""]"
